# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: velero-s3-creds
    namespace: velero
stringData:
    cloud: ENC[AES256_GCM,data:cO2xxoOqUa2oLiFrM7hBU2hDlo118owkawGPKtsCFLI3ZG3BxrA6yYVKH30bOF+D2tckrgIaSWXLENOjK2WixmYLZs7qMnKbg45j3eoZ/qA4llEMNb2wzPL4RvXWTacVNqu/TXsPr9Zz9uADG+vfgQ==,iv:QNxjeW0lFjkFS/EK0HQf1I5XOwo3q9ofAzjMWoFJgK8=,tag:1GQUAn0zaes8/A2WwR6Iig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3vm0a8frkxttp7kzmxfnuj240lmcwewe2fyj2z8flzmkreeeqnsm9aqnz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGL2V6dXdBbE80dEJmdVBp
            WkEybUl1R1JlUkVUN1VrYzcrWkFZTEdoZmhVCkMzaXZCdXRETnk0alJyRzVWZWJ5
            ZGhiTVFoSHNNVHlYajM0c1V4Zy9mdUEKLS0tIG5qa2lmTzA1Yzl3MW5ZQWhoZk5I
            d2d3MFFMN0FqalcvT29MbU8wZFFsN2cK1ImwnjE5VSu+7NeDt2gTsAXSyyByHfmi
            HhyXYgHDkM5HcSObPZnhpB02V36ZR3/zT0wOCg4jP5L0z8vD81i7Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-21T03:43:30Z"
    mac: ENC[AES256_GCM,data:PGluD7zWPsaHw/6Ou+MF1Oh04OiADug66gkZtwF5wlixlLuWw2ALNKjLMqPYM7oAW+M38bHxJyEXpnpGAYtYUrSiEwNWX06RdI0pSD7jiPMjsclKAQmGuzGL2zhmzP1xlVs/x7Vz9z6yhxBWL/fNCKdpc/EPI45i43R7O5Rq3QQ=,iv:CCAdj5kHYZvbPe8qv0iBGEI2S5HprjyfT+pyDMloXr8=,tag:xkh6gm1LSxgRSgIEd2dqDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
