apiVersion: v1
kind: Secret
metadata:
    name: velero-s3-creds
    namespace: velero
    stringData:
        cloud: ENC[AES256_GCM,data:LgFWTjxEtSyYeEg36ki6ORQkOPIs8WDcGdL0Qk65qhw8L6xZbaPumOBFOa0skTROkJfPQFbrBBkujla1PUI3pgrc/RabiMypVvoAs8JLI0y+LBFj+R2fpOYopIpgnXt4W55VRvFYQkN5iqIqVARmF91oAqFU,iv:GigbBTB02BI6/Xw9/RJJnZdadUU1vqvGXiBCFFiLDX4=,tag:gl7ppTNmtt8jMFzzbn0ljw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r3vm0a8frkxttp7kzmxfnuj240lmcwewe2fyj2z8flzmkreeeqnsm9aqnz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZFc0NEQ3SlRBTjZoQlRp
            TGl2dzlaa2FpOE45c2ZJZ3V6cytvT2k0emw4CnBzZlkwODRxTEowTExxSUk1QlR2
            cTcrSkxxamVFU3Nia2lGMXJBTS92ekEKLS0tIFh2dWRKQU9BWTRDRXF5WVR5ZHJj
            M0lFM0hCeDNSQlZrVXRGaFZCc0FzTTAKLU1xyLLy9HDDt4rd/xBGu5fr8oOenRb6
            hUcIxx/Lj2qkcuNvctakygSQkuntwe6/O6ft/GzZww9y5CAF9SIFcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-21T02:33:56Z"
    mac: ENC[AES256_GCM,data:tnoGjKQgMeJmMMTvxEn9ydiun8y9w+1xmCrXvjtQYZYuzQ9i+T9bUvTBc7QIAJOVvJDdLWM7yHaecE+gp6YajZOJOQIwF5zDqSr2mdZTWGFzBryI0MCrj/4Li6xqhcKBpdp/kH4zKGRfup680g8DQNADcjbPuocNTNR0jRMbMeU=,iv:yAGRlU3LniF4bdFGd80YLrwaC48K2L+Xx7Kr3X7ygf0=,tag:gef86+bIS5CFKBFEoFIcew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
