apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
  namespace: default
spec:
  ports:
  - port: 8123
    protocol: TCP
    targetPort: 8123
  type: NodePort
  sessionAffinity: None