apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hass-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi