---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rook-ceph
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-release
  interval: 1m0s
  targetNamespace: rook-ceph
  values:
    admissionController: null
    allowLoopDevices: false
    annotations: {}
    cephCommandsTimeoutSeconds: "15"
    crds:
      enabled: true
    csi:
      allowUnsupportedVersion: false
      cephFSFSGroupPolicy: File
      csiAddons:
        enabled: false
      enableCSIEncryption: false
      enableCSIHostNetwork: true
      enableCephfsDriver: true
      enableCephfsSnapshotter: true
      enableGrpcMetrics: false
      enableLiveness: false
      enableMetadata: false
      enableNFSSnapshotter: true
      enableOMAPGenerator: false
      enablePluginSelinuxHostMount: false
      enableRBDSnapshotter: true
      enableRbdDriver: true
      forceCephFSKernelClient: true
      grpcTimeoutInSeconds: 150
      nfs:
        enabled: false
      nfsFSGroupPolicy: File
      pluginPriorityClassName: system-node-critical
      provisionerPriorityClassName: system-cluster-critical
      provisionerReplicas: 2
      rbdFSGroupPolicy: File
      topology:
        enabled: false
    currentNamespaceOnly: false
    disableAdmissionController: false
    disableDeviceHotplug: false
    discoverDaemonUdev: null
    enableDiscoveryDaemon: false
    enableOBCWatchOperatorNamespace: true
    hostpathRequiresPrivileged: false
    image:
      pullPolicy: IfNotPresent
      repository: rook/ceph
      tag: VERSION
    logLevel: INFO
    monitoring:
      enabled: false
    nodeSelector: {}
    pspEnable: true
    rbacEnable: true
    resources:
      limits:
        memory: 258Mi
      requests:
        cpu: 10m
        memory: 128Mi
    tolerations: []
    unreachableNodeTolerationSeconds: 5

